import=[
    #"~/.config/alacritty/themes/catpuccin-mocha.toml"
    "~/.config/alacritty/themes/tinty.toml"
]

[env]
term = "xterm-256color"

[window]
padding={x = 0, y = 0}
blur=false
opacity=1.0

[font]
size=14.0
normal={family="BerkeleyMono Nerd Font"}
bold={family="BerkeleyMono Nerd Font"}
# normal={family="JetBrainsMono Nerd Font"}
# normal={family="BitstromWera Nerd Font"}
