import=[
    "~/.config/alacritty/themes/kanagawa.toml"
]

[env]
term = "xterm-256color"

[window]
padding={x = 0, y = 0}
blur=false
opacity=0.6

[font]
normal={family="JetBrainsMono Nerd Font"}
size=14.0
