import=[
    "~/.config/alacritty/themes/catpuccin-mocha.toml"
]

[env]
term = "xterm-256color"

[window]
padding={x = 0, y = 0}
blur=false
opacity=0.8

[font]
normal={family="Berkeley Mono"}
size=14.0
