-- " Radium
-- " A radioactive colorscheme.
-- " Authored by: https://github.com/dharmx
-- " License: GPL-3.0
--
-- " GNU GENERAL PUBLIC LICENSE
-- " Version 3, 29 June 2007
-- "
-- " Permissions of this strong copyleft license are conditioned on
-- " making available complete source code of licensed works and
-- " modifications, which include larger works using a licensed work,
-- " under the same license. Copyright and license notices must be
-- " preserved. Contributors provide an express grant of patent rights.
-- "
-- " Read the complete license here: https://www.gnu.org/licenses/gpl-3.0.en.html

local colors = {
    color_0 = "#101317",
    color_1 = "#1C2228",
    color_2 = "#36C692",
    color_3 = "#5FB0FC",
    color_4 = "#54CED6",
    color_5 = "#79DCAA",
    color_6 = "#7AB0DF",
    color_7 = "#70C0BA",
    color_8 = "#B77EE0",
    color_9 = "#C397D8",
    color_10 = "#D4D4D5",
    color_11 = "#F87070",
    color_12 = "#FB7373",
    color_13 = "#FCCF67",
    color_14 = "#FFE59E",
    color_15 = "#FFFFFF",
}

local radium = {
    colors = colors,
    groups = function(transparent)
        local groups = {
            Title = { bold = true, fg = "#66b3ff", },
            LazyProp = { bg = "#151a1f", fg = "#5FB0FC", },
            AlphaButtonLabelText = { fg = "#FFE59E", },
            AlphaFooting = { bold = true, fg = "#C397D8", },
            AlphaHeading = { fg = "#1A1F25", },
            AlphaKeyPrefix = { bg = "#7AB0DF", bold = true, fg = "#101317", },
            AlphaLoaded = { fg = "#24292F", },
            AlphaScroll = { fg = "#C397D8", },
            Bold = { bold = true, },
            BookmarkAnnotationLine = { fg = "#DDB1F2", },
            BookmarkAnnotationSign = { fg = "#C397D8", },
            BookmarkLine = { bg = "#31363B", },
            BookmarkSign = { fg = "#F87070", },
            Boolean = { bold = true, fg = "#F87070", },
            BufferLineBackground = { bg = "#14171E", fg = "#242A36", },
            BufferLineBuffer = { bg = "#14171E", fg = "#14171E", },
            BufferLineBufferSelected = { bg = "#7AB0DF", bold = true, fg = "#101317", },
            BufferLineBufferVisible = { bg = "#14171E", fg = "#7AB0DF", },
            BufferLineCloseButton = { bg = "#14171E", fg = "#F87070", },
            BufferLinecloseButtonSelected = { bg = "#7AB0DF", fg = "#101317", },
            BufferLineCloseButtonVisible = { bg = "#14171E", fg = "#F87070", },
            BufferLineDuplicate = { bg = "#14171E", fg = "#242A36", },
            BufferLineDuplicateSelected = { bg = "#14171E", fg = "#242A36", },
            BufferLineDuplicateVisible = { bg = "#14171E", fg = "#242A36", },
            BufferLineFill = { bg = "#101317", fg = "#313743", },
            BufferLineIndicatorSelected = { bg = "#7AB0DF", fg = "#7AB0DF", },
            BufferLineIndicatorVisible = { bg = "#14171E", fg = "#14171E", },
            BufferLineModified = { bg = "#14171E", fg = "#79DCAA", },
            BufferLineModifiedSelected = { bg = "#7AB0DF", fg = "#101317", },
            BufferLineModifiedVisible = { bg = "#14171E", fg = "#79DCAA", },
            BufferLineOffsetSeparator = { bg = "#7AB0DF", fg = "#7AB0DF", },
            BufferLinePick = { bg = "#14171E", bold = true, fg = "#D997C8", },
            BufferLinePickSelected = { bg = "#7AB0DF", bold = true, fg = "#E6CFA1", },
            BufferLinePickVisible = { bg = "#14171E", bold = true, fg = "#FCCF67", },
            BufferLineSeparator = { bg = "#14171E", fg = "#14171E", },
            BufferLineSeparatorSelected = { bg = "#7AB0DF", fg = "#7AB0DF", },
            BufferLineSeparatorVisible = { bg = "#14171E", fg = "#14171E", },
            BufferLineTabClose = { bg = "#101317", fg = "#F87070", },
            BufferLineTab = { bg = "#14171E", fg = "#242A36", },
            BufferLineTabSelected = { bg = "#101317", bold = true, fg = "#7AB0DF", },
            BufferLineTabSeparator = { bg = "#14171E", fg = "#14171E", },
            BufferLineTabSeparatorSelected = { fg = "#101317", },
            Character = { fg = "#E1C58D", },
            CmpItemAbbrDeprecated = { fg = "#3E4450", },
            CmpItemAbbr = { fg = "#BABABE", },
            CmpItemAbbrMatchFuzzy = { fg = "#FCCF67", },
            CmpItemAbbrMatch = { fg = "#79DCAA", },
            CmpItemKindClass = { fg = "#F87070", },
            CmpItemKindColor = { fg = "#7AB0DF", },
            CmpItemKindConstant = { fg = "#FF6666", },
            CmpItemKindConstructor = { fg = "#5FB0FC", },
            CmpItemKindEnum = { fg = "#54CED6", },
            CmpItemKindEnumMember = { fg = "#C297B9", },
            CmpItemKindEvent = { fg = "#7AAFF3", },
            CmpItemKindField = { fg = "#FFE69F", },
            CmpItemKindFile = { fg = "#FCCF67", },
            CmpItemKindFolder = { fg = "#FCCF67", },
            CmpItemKindFunction = { fg = "#BE8FD7", },
            CmpItemKind = { fg = "#3E4450", },
            CmpItemKindInterface = { fg = "#C397D8", },
            CmpItemKindKeyword = { fg = "#66B3FF", },
            CmpItemKindMethod = { fg = "#DC7272", },
            CmpItemKindModule = { fg = "#5FB0FC", },
            CmpItemKindOperator = { fg = "#70C0BA", },
            CmpItemKindProperty = { fg = "#54CED6", },
            CmpItemKindReference = { fg = "#FB7373", },
            CmpItemKindSnippet = { fg = "#FFE59E", },
            CmpItemKindStruct = { fg = "#5FB0FC", },
            CmpItemKindText = { fg = "#5FB0FC", },
            CmpItemKindTypeParameter = { fg = "#FFE49D", },
            CmpItemKindUnit = { fg = "#54CED6", },
            CmpItemKindValue = { fg = "#79DCAA", },
            CmpItemKindVariable = { fg = "#36C692", },
            CmpItemMenu = { fg = "#7AB0DF", },
            ColorColumn = { bg = "#111419", fg = "#171A20", },
            Comment = { fg = "#515C68", },
            Conceal = { fg = "#353E47", },
            Conditional = { fg = "#F87070", },
            Constant = { fg = "#FF6666", },
            CursorColumn = { bg = "#191D21", },
            Cursor = { bg = "#DFC184", fg = "#101317", },
            CursorLineFold = { bg = "#101317", fg = "#70C0BA", },
            CursorLine = { bg = "#191D21", },
            CursorLineNr = { bold = true, fg = "#FFE59E", },
            CursorLineSign = { bg = "#101317", },
            Debug = { fg = "#FB7373", },
            Decorator = { fg = "#FFE59E", },
            Define = { fg = "#C397D8", },
            Delimeter = { fg = "#7AB0DF", },
            Delimiter = { fg = "#FB7373", },
            DiagnosticError = { fg = "#F87070", },
            DiagnosticFloatingError = { fg = "#F87070", },
            DiagnosticFloatingHint = { fg = "#C397D8", },
            DiagnosticFloatingInfo = { fg = "#7AB0DF", },
            DiagnosticFloatingWarn = { fg = "#F97F7F", },
            DiagnosticHint = { fg = "#C397D8", },
            DiagnosticInfo = { fg = "#7AB0DF", },
            DiagnosticSignError = { fg = "#FB7373", },
            DiagnosticSignHint = { fg = "#C397D8", },
            DiagnosticSignInfo = { fg = "#7AB0DF", },
            DiagnosticSignWarn = { fg = "#F97F7F", },
            DiagnosticUnderlineError = { fg = "#F87070", },
            DiagnosticUnderlineHint = { fg = "#C397D8", },
            DiagnosticUnderlineInfo = { fg = "#7AB0DF", },
            DiagnosticUnderlineWarn = { fg = "#F97F7F", },
            DiagnosticVirtualTextError = { fg = "#F87070", },
            DiagnosticVirtualTextHint = { fg = "#C397D8", },
            DiagnosticVirtualTextInfo = { fg = "#7AB0DF", },
            DiagnosticVirtualTextWarn = { fg = "#F97F7F", },
            DiagnosticWarn = { fg = "#F97F7F", },
            DiffAdd = { fg = "#79DCAA", reverse = true, },
            DiffChange = { fg = "#C397D8", reverse = true, },
            DiffDelete = { fg = "#F87070", reverse = true, },
            DiffText = { fg = "#7AB0DF", reverse = true, },
            DiffviewCursorLine = { bg = "#191D21", },
            DiffviewDiffAddAsDelete = { fg = "#F87070", reverse = true, },
            DiffviewDiffDelete = { fg = "#515C68", },
            DiffviewDim1 = { fg = "#515C68", },
            DiffviewEndOfBuffer = { fg = "#C397D8", },
            DiffviewFilePanelConflicts = { fg = "#F97F7F", },
            DiffviewFilePanelCounter = { bold = true, fg = "#36C692", },
            DiffviewFilePanelFileName = { fg = "#D4D4D5", },
            DiffviewFilePanelPath = { fg = "#515C68", },
            DiffviewFilePanelRootPath = { bold = true, fg = "#F87070", },
            DiffviewFilePanelSelected = { fg = "#F87070", },
            DiffviewFilePanelTitle = { bold = true, fg = "#F87070", },
            DiffviewFolderName = { fg = "#FFE59E", },
            DiffviewFolderSign = { fg = "#F96262", },
            DiffviewNonText = { fg = "#222931", },
            DiffviewNormal = { bg = "#101317", fg = "#D4D4D5", },
            DiffviewPrimary = { fg = "#BE8FD7", },
            DiffviewReference = { fg = "#BE8FD7", },
            DiffviewSecondary = { fg = "#79DCAA", },
            DiffviewSignColumn = { bg = "#101317", fg = "#D4D4D5", },
            DiffviewStatusIgnored = { fg = "#515C68", },
            DiffviewStatusLine = { bg = "#101317", fg = "#7AB0DF", },
            DiffviewStatusLineNC = { fg = "#7AB0DF", },
            DiffviewWinSeparator = { fg = "#171C21", },
            Directory = { fg = "#FFE59E", },
            EndOfBuffer = { fg = "#C397D8", },
            Error = { fg = "#F76262", },
            ErrorMsg = { fg = "#F87070", bg = "#151A1F", },
            Exception = { fg = "#36C692", },
            FidgetTask = { fg = "#1A1E27", },
            FidgetTitle = { bold = true, fg = "#36C692", },
            FloatBorder = { bg = "#151A1F", fg = "#151A1F", },
            Float = { fg = "#F3A4F1", },
            FloatShadow = { bg = "#000000", blend = 80 },
            FloatShadowThrough = { bg = "#000000", blend = 100 },
            FocusedSymbol = { bg = "#666666", fg = "#FFA0A0", },
            FoldColumn = { bg = "#101317", fg = "#70C0BA", },
            Folded = { bg = "#101317", fg = "#282F3C", },
            Function = { fg = "#BE8FD7", },
            GitSignsAdd = { fg = "#7AB0DF", },
            GitSignsAddInline = { reverse = true, },
            GitSignsAddLn = { fg = "#7AB0DF", },
            GitSignsAddLnInline = { reverse = true, },
            GitSignsAddNr = { fg = "#5FB0FC", },
            GitSignsAddPreview = { fg = "#79DCAA", reverse = true, },
            GitSignsChangedelete = { fg = "#21272D", },
            GitSignsChangedeleteLn = { fg = "#CB9FE0", },
            GitSignsChangedeleteNr = { fg = "#B77EE0", },
            GitSignsChange = { fg = "#21272D", },
            GitSignsChangeInline = { reverse = true, },
            GitSignsChangeLn = { fg = "#CB9FE0", },
            GitSignsChangeLnInline = { reverse = true, },
            GitSignsChangeNr = { fg = "#B77EE0", },
            GitSignsCurrentLineBlame = { fg = "#222931", },
            GitSignsDelete = { fg = "#FB7373", },
            GitSignsDeleteInline = { reverse = true, },
            GitSignsDeleteLn = { fg = "#F87070", },
            GitSignsDeleteLnInline = { reverse = true, },
            GitSignsDeleteNr = { fg = "#FE7676", },
            GitSignsDeletePreview = { fg = "#F87070", reverse = true, },
            GitSignsDeleteVirtLn = { fg = "#F87070", reverse = true, },
            GitSignsDeleteVirtLnInLine = { reverse = true, },
            GitSignsStagedAdd = { fg = "#3D586F", },
            GitSignsStagedAddLn = { fg = "#3D586F", },
            GitSignsStagedAddNr = { fg = "#2F587E", },
            GitSignsStagedChangedelete = { fg = "#101316", },
            GitSignsStagedChangedeleteLn = { fg = "#654F70", },
            GitSignsStagedChangedeleteNr = { fg = "#5B3F70", },
            GitSignsStagedChange = { fg = "#101316", },
            GitSignsStagedChangeLn = { fg = "#654F70", },
            GitSignsStagedChangeNr = { fg = "#5B3F70", },
            GitSignsStagedDelete = { fg = "#7D3939", },
            GitSignsStagedDeleteLn = { fg = "#7C3838", },
            GitSignsStagedDeleteNr = { fg = "#7F3B3B", },
            GitSignsStagedTopdelete = { fg = "#7D3939", },
            GitSignsStagedTopdeleteNr = { fg = "#7F3B3B", },
            GitSignsTopdelete = { fg = "#FB7373", },
            GitSignsTopdeleteNr = { fg = "#FE7676", },
            GitSignsUntracked = { fg = "#7AB0DF", },
            GitSignsUntrackedLn = { fg = "#7AB0DF", },
            GitSignsUntrackedNr = { fg = "#5FB0FC", },
            HarpoonBorder = { bg = "#151A1F", fg = "#151A1F", },
            HarpoonCurrentFile = { bold = true, fg = "#FFE59E", },
            HarpoonCursor = { bg = "#1A1F25", fg = "#7AB0DF", },
            HarpoonTitle = { bg = "#F87070", fg = "#171C21", },
            HarpoonWindow = { bg = "#151A1F", fg = "#BABABE", },
            HighlightUrl = { fg = "#70C0BA", undercurl = true },
            HlSearchFloat = { bg = "#1A1E27", fg = "#D0A4E5", },
            HlSearchLens = { bg = "#1A1E27", fg = "#87BDEC", },
            HlSearchLensNear = { bg = "#FFE28F", bold = true, fg = "#101317", },
            HlSearchNear = { bg = "#1A1E27", bold = true, fg = "#7DCDC7", },
            Identifier = { fg = "#36C692", },
            InclineBG = { bg = "#171C21", },
            InclineBGNC = { bg = "#14171E", },
            InclineCursorLine = { bg = "#151A1F", },
            InclineCursorLineNC = { bg = "#141A1D", },
            InclineFG = { fg = "#D4D4D5", },
            InclineFGNC = { fg = "#C397D8", },
            InclineNormal = { bg = "#151A1F", fg = "#BABABE", },
            InclineNormalNC = { bg = "#151A1F", fg = "#BABABE", },
            InclineThemeBG = { bg = "#FFE59E", },
            Include = { bold = true, fg = "#6AA6DF", },
            IncSearch = { bg = "#70C0BA", fg = "#101317", },
            IndentBlanklineChar = { fg = "#22272C", },
            IndentBlanklineContextChar = { fg = "#7AB0DF", },
            IndentBlanklineContextStart = { bg = "#16191F", },
            Italic = { italic = true },
            JaqBorder = { bg = "#161921", },
            JaqWin = { bg = "#161921", },
            Keyword = { fg = "#66B3FF", },
            Label = { fg = "#F87070", },
            LightBulbFloatWin = { fg = "#FCCF67", },
            LightBulbSign = { fg = "#FFE59E", },
            LightBulbVirtualText = { fg = "#FFE59E", },
            LineNrAbove = { fg = "#2E3645", },
            LineNrBelow = { fg = "#2E3645", },
            LineNr = { fg = "#2E3645", },
            LspDiagnosticsSignError = { fg = "#FB7373", },
            LspDiagnosticsSignHint = { fg = "#C397D8", },
            LspDiagnosticsSignInfo = { fg = "#7AB0DF", },
            LspDiagnosticsSignWarn = { fg = "#FF7D7D", },
            LspReferenceRead = { bg = "#161921", bold = true, fg = "#82B8E7", },
            LspReferenceText = { bg = "#161921", bold = true, fg = "#CB9FE0", },
            LspReferenceWrite = { bg = "#161921", bold = true, fg = "#DC97CA", },
            LspSignatureActiveParameter = { bg = "#161921", bold = true, fg = "#78C8C2", },
            luaCommentDelimiter = { fg = "#515C68", },
            luaComment = { fg = "#515C68", },
            luaCondElse = { fg = "#F87070", },
            luaCond = { fg = "#F87070", },
            luaConstant = { fg = "#FF6666", },
            luaError = { fg = "#F76262", },
            luaFor = { fg = "#B77EE0", },
            luaFunc = { fg = "#36C692", },
            luaFunction = { fg = "#BE8FD7", },
            luaLabel = { fg = "#F87070", },
            luaMetaMethod = { fg = "#BE8FD7", },
            luaNumber = { fg = "#54CED6", },
            luaOperator = { fg = "#70C0BA", },
            luaParenError = { fg = "#F76262", },
            luaRepeat = { fg = "#B77EE0", },
            luaSpecial = { fg = "#C397D8", },
            luaStatement = { fg = "#F87070", },
            luaString2 = { fg = "#79DCAA", },
            luaStringDelimiter = { fg = "#79DCAA", },
            luaString = { fg = "#79DCAA", },
            luaSymbolOperator = { fg = "#70C0BA", },
            luaTable = { fg = "#5FB0FC", },
            Macro = { fg = "#F98989", },
            MatchBackground = { bg = "#111419", fg = "#171A20", },
            MatchParenCur = { bg = "#202530", bold = true, },
            MatchParen = { bg = "#202530", bold = true, },
            MatchWord = { bg = "#202530", bold = true, },
            ModeMsg = { bold = true, fg = "#7AB0DF", },
            monarkCommand = { fg = "#5FB0FC", },
            monarkInsert = { fg = "#7AB0DF", },
            monarkNormal = { fg = "#79DCAA", },
            monarkReplace = { fg = "#C397D8", },
            MonarkSelect = { fg = "#54CED6", },
            MonarkTerminal = { fg = "#54CED6", },
            MonarkVisualBlock = { fg = "#FCCF67", },
            monarkVisual = { fg = "#FFE59E", },
            MonarkVisualLine = { fg = "#F87070", },
            MoreMsg = { fg = "#FFE59E", },
            MsgArea = { fg = "#CACACD", },
            MsgSeparator = { fg = "#C397D8", },
            NavicIconsArray = { fg = "#FCCF67", },
            NavicIconsBoolean = { bold = true, fg = "#F87070", },
            NavicIconsClass = { fg = "#F75858", },
            NavicIconsConstant = { bold = true, fg = "#FF6666", },
            NavicIconsConstructor = { fg = "#5FB0FC", },
            NavicIconsEnum = { fg = "#7AB0DF", },
            NavicIconsEnumMember = { fg = "#F96262", },
            NavicIconsEvent = { fg = "#79CFAA", },
            NavicIconsField = { fg = "#36C692", },
            NavicIconsFile = { fg = "#FFE59E", },
            NavicIconsFunction = { fg = "#BE8FD7", },
            NavicIconsInterface = { fg = "#FF7070", },
            NavicIconsKey = { fg = "#F87070", },
            NavicIconsMethod = { fg = "#B77EE0", },
            NavicIconsModule = { fg = "#F98989", },
            NavicIconsNull = { bold = true, fg = "#FFDF85", },
            NavicIconsNumber = { fg = "#54CED6", },
            NavicIconsObject = { fg = "#FFE390", },
            NavicIconsOperator = { fg = "#70C0BA", },
            NavicIconsPackage = { bold = true, fg = "#6AA6DF", },
            NavicIconsProperty = { fg = "#54CED6", },
            NavicIconsString = { fg = "#79DCAA", },
            NavicIconsStruct = { fg = "#5FB0FC", },
            NavicIconsTypeParameter = { fg = "#FFE49D", },
            NavicIconsVariable = { bold = true, fg = "#FA6969", },
            NavicSeparator = { fg = "#7AB0DF", },
            NavicText = { fg = "#AAAAAF", },
            NeogitBranch = { bold = true, fg = "#36C692", },
            NeogitCommitViewHeader = { bg = "#7AB0DF", bold = true, fg = "#101317", },
            NeogitDiffAdd = transparent and { bg = nil, fg = "#7AB0DF" } or { bg = "#16191D", fg = "#7AB0DF", },
            NeogitDiffAddHighlight = transparent and { bg = nil, fg = "#7AB0DF" } or { bg = "#16191D", fg = "#7AB0DF", },
            NeogitDiffContextHighlight = { bg = "#1A1D24", },
            NeogitDiffDelete = transparent and { bg = nil, fg = "#F87070", } or { bg = "#1C1F22", fg = "#F87070", },
            NeogitDiffDeleteHighlight = transparent and { bg = nil, fg = "#F87070", } or
                { bg = "#1C1F22", fg = "#F87070", },
            NeogitFilePath = { fg = "#70C0BA", },
            NeogitFold = { bg = "#101317", fg = "#54CED6", },
            NeogitHunkHeader = { bg = "#171C21", fg = "#FFE59E", },
            NeogitHunkHeaderHighlight = { bg = "#FFE59E", fg = "#101317", },
            NeogitNotificationError = { bg = "#101317", fg = "#F87070", },
            NeogitNotificationInfo = { bg = "#101317", fg = "#7AB0DF", },
            NeogitNotificationWarning = { bg = "#101317", fg = "#FFE59E", },
            NeogitObjectId = { fg = "#C397D8", },
            NeogitRebaseDone = { bold = true, fg = "#79DCAA", },
            NeogitRebasing = { bold = true, fg = "#FFE59E", },
            NeogitRecentcommits = { bold = true, fg = "#79DCAA", },
            NeogitRemote = { bold = true, fg = "#FCCF67", },
            NeogitStagedchanges = { bold = true, fg = "#FFE59E", },
            NeogitStashes = { bold = true, fg = "#70C0BA", },
            NeogitStash = { fg = "#70C0BA", },
            NeogitUnmergedchanges = { bold = true, fg = "#36C692", },
            NeogitUnmergedInto = { fg = "#7AB0DF", },
            NeogitUnpulledchanges = { bold = true, fg = "#54CED6", },
            NeogitUnpulledFrom = { fg = "#54CED6", },
            NeogitUnstagedchanges = { bold = true, fg = "#FB7373", },
            NeogitUntrackedfiles = { bold = true, fg = "#5FB0FC", },
            NonText = { fg = "#222931", },
            NormalFloat = { bg = "#151A1F", fg = "#BABABE", },
            Normal = transparent and { bg = nil, fg = "#D4D4D5" } or { bg = "#101317", fg = "#D4D4D5" },
            NotifyBackground = { bg = "#101317", fg = "#D4D4D5", },
            NotifyDEBUGBody = { bg = "#171C21", fg = "#C397D8", },
            NotifyDEBUGBorder = { bg = "#171C21", fg = "#171C21", },
            NotifyDEBUGIcon = { bg = "#171C21", fg = "#B77EE0", },
            NotifyDEBUGTitle = { bg = "#171C21", fg = "#C397D8", },
            NotifyERRORBody = { bg = "#171C21", fg = "#F87070", },
            NotifyERRORBorder = { bg = "#171C21", fg = "#171C21", },
            NotifyERRORIcon = { bg = "#171C21", fg = "#FB7373", },
            NotifyERRORTitle = { bg = "#171C21", fg = "#F87070", },
            NotifyINFOBody = { bg = "#171C21", fg = "#7AB0DF", },
            NotifyINFOBorder = { bg = "#171C21", fg = "#171C21", },
            NotifyINFOIcon = { bg = "#171C21", fg = "#5FB0FC", },
            NotifyINFOTitle = { bg = "#171C21", fg = "#7AB0DF", },
            NotifyLogTime = { fg = "#515C68", },
            NotifyLogTitle = { fg = "#FB7373", },
            NotifyTRACEBody = { bg = "#171C21", fg = "#79DCAA", },
            NotifyTRACEBorder = { bg = "#171C21", fg = "#171C21", },
            NotifyTRACEIcon = { bg = "#171C21", fg = "#36C692", },
            NotifyTRACETitle = { bg = "#171C21", fg = "#79DCAA", },
            NotifyWARNBody = { bg = "#171C21", fg = "#FFE59E", },
            NotifyWARNBorder = { bg = "#171C21", fg = "#171C21", },
            NotifyWARNIcon = { bg = "#171C21", fg = "#FCCF67", },
            NotifyWARNTitle = { bg = "#171C21", fg = "#FFE59E", },
            NUICancel = { fg = "#222931", },
            NUIHeading = { bg = "#151A1F", fg = "#F87070", },
            NUILine = { bg = "#151A1F", fg = "#22272C", },
            NUINo = { fg = "#F87070", },
            NUINormal = { bg = "#151A1F", fg = "#151A1F", },
            NUIPrompt = { bg = "#151A1F", fg = "#7AB0DF", },
            NUIText = { bg = "#151A1F", fg = "#BABABE", },
            NUIYes = { fg = "#7AB0DF", },
            Number = { fg = "#54CED6", },
            NvimTreeBookmark = { fg = "#FFE59E", },
            NvimTreeClosedFolderIcon = { fg = "#B77EE0", },
            NvimTreeCursorLine = { fg = "#12151B", },
            NvimTreeCursorLineNr = { bold = true, fg = "#36C692", },
            NvimTreeEmptyFolderName = { fg = "#B58ED1", },
            NvimTreeExecFile = { fg = "#D997C8", },
            NvimTreeFileDeleted = { fg = "#FB7373", },
            NvimTreeFileDirty = { fg = "#70C0BA", },
            NvimTreeFileIgnored = { fg = "#171C21", },
            NvimTreeFileMerge = { fg = "#36C692", },
            NvimTreeFileNew = { fg = "#FFE59E", },
            NvimTreeFileRenamed = { fg = "#5FB0FC", },
            NvimTreeFileStaged = { fg = "#D997C8", },
            NvimTreeFolderIcon = { fg = "#B77EE0", },
            NvimTreeFolderName = { fg = "#B77EE0", },
            NvimTreeGitDeleted = { fg = "#F87070", },
            NvimTreeGitDirty = { fg = "#70C0BA", },
            NvimTreeGitIgnored = { fg = "#171C21", },
            NvimTreeGitMerge = { fg = "#54CED6", },
            NvimTreeGitNew = { fg = "#FFE59E", },
            NvimTreeGitRenamed = { fg = "#5FB0FC", },
            NvimTreeGitStaged = { fg = "#D997C8", },
            NvimTreeImageFile = { fg = "#B77EE0", },
            NvimTreeIndentMarker = { fg = "#1D2529", },
            NvimTreeNormal = { bg = "#0C0E11", fg = "#BABABE", },
            NvimTreeNormalNC = { bg = "#0C0E11", fg = "#BABABE", },
            NvimTreePopup = { fg = "#7AB0DF", },
            NvimTreeRootFolder = { bold = true, fg = "#F87070", },
            NvimTreeSymlink = { fg = "#70C0BA", },
            NvimTreeVertSplit = { bg = "#0C0E11", fg = "#0C0E11", },
            NvimTreeWindowPicker = { bg = "#191C24", fg = "#7AB0DF", },
            NvimTreeWinSeparator = { bg = "#0C0E11", fg = "#0C0E11", },
            NvimUnaryMinus = { fg = "#70C0BA", },
            NvimUnaryOperator = { fg = "#70C0BA", },
            NvimUnaryPlus = { fg = "#70C0BA", },
            Operator = { fg = "#70C0BA", },
            Pmenu = { bg = "#171D20", fg = "#A0A0A5", },
            PmenuSbar = { bg = "#171D20", fg = "#A0A0A5", },
            PmenuSel = { bg = "#1B2226", fg = "#ADADB2", },
            PmenuThumb = { bg = "#1E2225", },
            PreCondit = { fg = "#F96262", },
            PreProc = { fg = "#F96262", },
            Question = { fg = "#79DCAA", },
            QuickFixLine = { bg = "#FFE59E", fg = "#101317", },
            TSRainbowBlue = { fg = "#94CAF9", },
            TSRainbowCyan = { fg = "#79CAFF", },
            TSRainbowGreen = { fg = "#50E0AC", },
            TSRainbowOrange = { fg = "#FF9393", },
            TSRainbowRed = { fg = "#F96262", },
            TSRainbowViolet = { fg = "#D098FF", },
            TSRainbowYellow = { fg = "#FFE981", },
            RedrawDebugClear = { bg = "#FFFF00", },
            RedrawDebugComposed = { bg = "#008000", },
            RedrawDebugNormal = { reverse = true, },
            RedrawDebugRecompose = { bg = "#FF0000", },
            Repeat = { fg = "#B77EE0", },
            RnvimrCurses = { bg = "#101317", fg = "#D4D4D5", },
            RnvimrNormal = { bg = "#151A1F", fg = "#BABABE", },
            ScrollbarCursor = { fg = "#54CED6", },
            ScrollbarCursorHandle = { bg = "#20272E", fg = "#54CED6", },
            ScrollbarError = { fg = "#F87070", },
            ScrollbarErrorHandle = { fg = "#F87070", },
            ScrollbarGitAdd = { fg = "#7AB0DF", },
            ScrollbarGitAddHandle = { fg = "#82B8E7", },
            ScrollbarGitChange = { fg = "#C397D8", },
            ScrollbarGitChangeHandle = { fg = "#BD84E6", },
            ScrollbarGitDelete = { fg = "#F87070", },
            ScrollbarGitDeleteHandle = { fg = "#FF7B7B", },
            ScrollbarHandle = { fg = "#7AB0DF", },
            ScrollbarHint = { fg = "#C397D8", },
            ScrollbarHintHandle = { fg = "#B77EE0", },
            ScrollbarInfo = { fg = "#7AB0DF", },
            ScrollbarInfoHandle = { fg = "#7AB0DF", },
            ScrollbarMisc = { fg = "#DC97CA", },
            ScrollbarMiscHandle = { fg = "#70C0BA", },
            ScrollbarSearch = { fg = "#FFE59E", },
            ScrollbarSearchHandle = { fg = "#FFD76F", },
            ScrollbarWarn = { fg = "#F97F7F", },
            ScrollbarWarnHandle = { fg = "#FA6969", },
            Search = { bg = "#FFE59E", fg = "#101317", },
            SignColumn = transparent and { bg = nil } or { bg = "#101317", },
            SpecialChar = { fg = "#C397D8", },
            SpecialComment = { fg = "#FFDF8F", },
            Special = { fg = "#FB7373", },
            SpecialKey = { bold = true, fg = "#FFE59E", },
            SpellBad = { fg = "#F87070", },
            SpellCap = { fg = "#FCCF67", },
            SpellLocal = { fg = "#FB7373", },
            SpellRare = { fg = "#54CED6", },
            Statement = { fg = "#F87070", },
            StatusLine = { fg = "#191D21", bg = "#7AB0DF", },
            StatusLineNC = { fg = "#7AB0DF", bg = "#101317", },
            StorageClass = { fg = "#F75858", },
            String = { fg = "#79DCAA", },
            Structure = { fg = "#5FB0FC", },
            Substitute = { bg = "#B77EE0", fg = "#101317", },
            TabLine = { bg = "#101317", bold = true, fg = "#2C3640", },
            TabLineFill = { fg = "#101317", bg = "#7AB0DF", },
            TabLineSel = { bg = "#7AB0DF", bold = true, fg = "#101317", },
            Tag = { fg = "#7AB0DF", },
            TelescopeMatching = { bold = true, fg = "#DC97CA", },
            TelescopePreviewBorder = { bg = "#0E1014", fg = "#0E1014", },
            TelescopePreviewLine = { bg = "#15181E", },
            TelescopePreviewNormal = { bg = "#0E1014", fg = "#BABABE", },
            TelescopePreviewTitle = { bg = "#7AB0DF", fg = "#101317", },
            TelescopePromptCounter = { bg = "#12151B", bold = true, fg = "#D997C8", },
            TelescopePromptNormal = { bg = "#12151B", fg = "#BABABE", },
            TelescopePromptPrefix = { bg = "#12151B", fg = "#F87070", },
            TelescopePromptTitle = { bg = "#F87070", fg = "#101317", },
            TelescopePromptBorder = { bg = "#12151B", fg = "#2E7DC2", },
            TelescopeResultsBorder = { bg = "#0C0E11", fg = "#0C0E11", },
            TelescopeResultsNormal = { bg = "#0C0E11", fg = "#BABABE", },
            TelescopeResultsTitle = { bg = "#79DCAA", fg = "#101317", },
            TelescopeSelectionCaret = { bg = "#101317", fg = "#FB7373", },
            TelescopeSelection = { bg = "#101317", fg = "#54CED6", },
            TermCursor = { reverse = true, },
            TodoBgBUG = { bg = "#F87070", bold = true, fg = "#171C21", },
            TodoBgCHORE = { bg = "#70C0BA", bold = true, fg = "#171C21", },
            TodoBgCLEAN = { bg = "#7AB0DF", bold = true, fg = "#171C21", },
            TodoBgDEMO = { bg = "#5FB0FC", bold = true, fg = "#171C21", },
            TodoBgFIX = { bg = "#FFE59E", bold = true, fg = "#171C21", },
            TodoBgHACK = { bg = "#79DCAA", bold = true, fg = "#171C21", },
            TodoBgIMPROVE = { bg = "#5FB0FC", bold = true, fg = "#171C21", },
            TodoBgNOTE = { bg = "#36C692", bold = true, fg = "#171C21", },
            TodoBgPERF = { bg = "#FCCF67", bold = true, fg = "#171C21", },
            TodoBgTEST = { bg = "#54CED6", bold = true, fg = "#171C21", },
            TodoBgTODO = { bg = "#C397D8", bold = true, fg = "#171C21", },
            TodoBgUPDATE = { bg = "#B77EE0", bold = true, fg = "#171C21", },
            TodoBgWANTS = { bg = "#FFEDA6", bold = true, fg = "#171C21", },
            TodoBgWARN = { bg = "#E17272", bold = true, fg = "#171C21", },
            TodoFgBUG = { fg = "#F87070", },
            TodoFgCHORE = { fg = "#70C0BA", },
            TodoFgCLEAN = { fg = "#7AB0DF", },
            TodoFgDEMO = { fg = "#5FB0FC", },
            TodoFgFIX = { fg = "#FFE59E", },
            TodoFgHACK = { fg = "#79DCAA", },
            TodoFgIMPROVE = { fg = "#5FB0FC", },
            TodoFgNOTE = { fg = "#36C692", },
            TodoFgPERF = { fg = "#FCCF67", },
            TodoFgTEST = { fg = "#54CED6", },
            TodoFgTODO = { fg = "#C397D8", },
            TodoFgUPDATE = { fg = "#B77EE0", },
            TodoFgWANTS = { fg = "#FFEDA6", },
            TodoFgWARN = { fg = "#E17272", },
            Todo = { fg = "#FFE59E", },
            TodoSignBUG = { bg = "#101317", fg = "#F87070", },
            TodoSignCHORE = { bg = "#101317", fg = "#70C0BA", },
            TodoSignCLEAN = { bg = "#101317", fg = "#7AB0DF", },
            TodoSignDEMO = { bg = "#101317", fg = "#5FB0FC", },
            TodoSignFIX = { bg = "#101317", fg = "#FCCF67", },
            TodoSignHACK = { bg = "#101317", fg = "#79DCAA", },
            TodoSignIMPROVE = { bg = "#101317", fg = "#5FB0FC", },
            TodoSignNOTE = { bg = "#101317", fg = "#36C692", },
            TodoSignPERF = { bg = "#101317", fg = "#FCCF67", },
            TodoSignTEST = { bg = "#101317", fg = "#54CED6", },
            TodoSignTODO = { bg = "#101317", fg = "#C397D8", },
            TodoSignUPDATE = { bg = "#101317", fg = "#B77EE0", },
            TodoSignWANTS = { bg = "#101317", fg = "#FFEDA6", },
            TodoSignWARN = { bg = "#101317", fg = "#E17272", },
            TreesitterContext = { bg = "#171A20", },
            TroubleNormal = { bg = "#0C0E11", },
            Typedef = { fg = "#C397D8", },
            Type = { fg = "#F87070", },
            Underlined = { undercurl = true },
            UndotreeBranch = { fg = "#FF6666", },
            UndotreeCurrent = { fg = "#F87070", },
            UndotreeFirstNode = { fg = "#BE8FD7", },
            UndotreeHead = { fg = "#36C692", },
            UndotreeHelp = { fg = "#515C68", },
            UndotreeHelpKey = { bold = true, fg = "#F87070", },
            UndotreeHelpTitle = { fg = "#F87070", },
            UndotreeNext = { fg = "#7AB0DF", },
            UndotreeNodeCurrent = { fg = "#E1C58D", },
            UndotreeNode = { fg = "#79DCAA", },
            UndotreeSavedBig = { bg = "#202530", bold = true, },
            UndotreeSavedSmall = { fg = "#FB7373", },
            UndotreeSeq = { fg = "#515C68", },
            UndotreeTimeStamp = { fg = "#70C0BA", },
            VertSplit = { fg = "#171C21", },
            VirtColumn = { bg = "#101317", fg = "#171A20", },
            Visual = { bg = "#333333", },
            WarningMsg = { fg = "#FB7373", },
            WhichKeyBorder = { bg = "#0E1014", },
            WhichKeyDesc = { fg = "#FFE59E", },
            WhichKeyFloat = { bg = "#0E1014", },
            WhichKeyGroup = { bold = true, fg = "#F87070", },
            WhichKey = { fg = "#C397D8", },
            WhichKeySeparator = { fg = "#7AB0DF", },
            WhichKeyValue = { fg = "#929299", },
            Whitespace = { fg = "#1E222A", },
            WildMenu = { bg = "#7AB0DF", fg = "#101317", },
            WinBar = { bold = true, },
            WinBarNC = { bold = true, },
            WinSeparator = { fg = "#171C21", },

            ["@boolean"] = { bold = true, fg = "#F87070", },
            ["@character"] = { fg = "#E1C58D", },
            ["@comment"] = { fg = "#515C68", },
            ["@conditional"] = { fg = "#F87070", },
            ["@constant.builtin"] = { bold = true, fg = "#FFDF85", },
            ["@constant"] = { bold = true, fg = "#FF6666", },
            ["@constant.macro"] = { fg = "#E37070", },
            ["@constructor"] = { fg = "#5FB0FC", },
            ["@debug"] = { fg = "#7AAFC5", },
            ["@define"] = { fg = "#C397D8", },
            ["@exception"] = { fg = "#6AA6DF", },
            ["@field"] = { fg = "#36C692", },
            ["@float"] = { fg = "#F3A4F1", },
            ["@function.builtin"] = { bold = true, fg = "#36C692", },
            ["@function"] = { fg = "#BE8FD7", },
            ["@function.macro"] = { fg = "#FF7070", },
            ["@include"] = { bold = true, fg = "#6AA6DF", },
            ["@keyword.function"] = { fg = "#FB7373", },
            ["@keyword"] = { fg = "#66B3FF", },
            ["@keyword.operator"] = { fg = "#70C0BA", },
            ["@keyword.return"] = { fg = "#66B3FF", },
            ["@label"] = { fg = "#F87070", },
            ["@lua.constant.cmd"] = { bold = true, fg = "#60B0FC", },
            ["@lua.constant.vim"] = { bold = true, fg = "#FF6666", },
            ["@lua.function.pcall"] = { bold = true, fg = "#F98989", },
            ["@lua.parameter.self"] = { bold = true, fg = "#FFCE66", },
            ["@macro"] = { fg = "#F98989", },
            ["@method"] = { fg = "#B77EE0", },
            ["@namespace"] = { fg = "#60B0FC", },
            ["@number"] = { fg = "#54CED6", },
            ["@operator"] = { fg = "#70C0BA", },
            ["@parameter"] = { fg = "#FFE49D", },
            ["@preproc"] = { fg = "#F96262", },
            ["@property"] = { fg = "#54CED6", },
            ["@punctuation.bracket"] = { fg = "#FF7D7D", },
            ["@punctuation.delimiter"] = { fg = "#7AB0DF", },
            ["@punctuation"] = { fg = "#7AB0DF", },
            ["@repeat"] = { fg = "#B77EE0", },
            ["@storageclass"] = { fg = "#F75858", },
            ["@string.escape"] = { fg = "#E5E49D", },
            ["@string"] = { fg = "#79DCAA", },
            ["@string.regex"] = { fg = "#FFE390", },
            ["@string.special"] = { fg = "#FCCF67", },
            ["@structure"] = { fg = "#5FB0FC", },
            ["@tag"] = { fg = "#7AB0DF", },
            ["@text"] = { fg = "#D4D4D5", },
            ["@text.literal"] = { fg = "#79CFAA", },
            ["@text.reference"] = { fg = "#7AB0DF", },
            ["@text.title"] = { bold = true, fg = "#FA6969", },
            ["@text.todo"] = { fg = "#FFE59E", },
            ["@text.underline"] = { undercurl = true },
            ["@text.uri"] = { fg = "#70C0BA", undercurl = true },
            ["@type.definition"] = { fg = "#C397D8", },
            ["@type"] = { fg = "#F87070", },
            ["@variable"] = { fg = "#D4D4D5", },

            ["@lsp.type.boolean"] = { link = "@boolean" },
            ["@lsp.type.builtinType"] = { link = "@type.builtin" },
            ["@lsp.type.comment"] = { link = "@comment" },
            ["@lsp.type.enum"] = { link = "@type" },
            ["@lsp.type.enumMember"] = { link = "@constant" },
            ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
            ["@lsp.type.formatSpecifier"] = { link = "@punctuation.special" },
            ["@lsp.type.interface"] = { link = "Structur" },
            ["@lsp.type.keyword"] = { link = "@keywor" },
            ["@lsp.type.namespace"] = { link = "@namespac" },
            ["@lsp.type.number"] = { link = "@number" },
            ["@lsp.type.operator"] = { link = "@operator" },
            ["@lsp.type.parameter"] = { link = "@parameter" },
            ["@lsp.type.property"] = { link = "@property" },
            ["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
            ["@lsp.type.typeAlias"] = { link = "@type.definition" },
            ["@lsp.type.unresolvedReference"] = { link = "@error" },
            ["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
            ["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
            ["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
            ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
            ["@lsp.typemod.keyword.async"] = { link = "@keyword.coroutine" },
            ["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
            ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
            ["@lsp.typemod.operator.injected"] = { link = "@operator" },
            ["@lsp.typemod.string.injected"] = { link = "@string" },
            ["@lsp.typemod.type.defaultLibrary"] = { link = "@type.builtin" },
            ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
            ["@lsp.typemod.variable.injected"] = { link = "@variable" },
        }
        return groups
    end
}

return radium
