theme = "gruvbox"

[editor]
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[keys.normal]
minus = "file_picker_in_current_buffer_directory"

[keys.insert]
j = { k = "normal_mode" }
