vim.opt.fillchars = { vert = '│', horiz = '─' }
local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.current_buffer_fuzzy_find)
vim.keymap.set("n", "<leader>fgc", builtin.git_commits)
vim.keymap.set("n", "<leader>fgb", builtin.git_branches)
vim.keymap.set("n", "<leader>fr", builtin.resume)
vim.keymap.set("n", "<leader>fc", builtin.commands)
vim.keymap.set("n", "<leader>fo", builtin.vim_options)
vim.keymap.set("n", "<leader>fht", builtin.help_tags)
vim.keymap.set("n", "<leader>fpr", builtin.reloader)
vim.keymap.set("n", "<leader>fb", builtin.buffers)
vim.keymap.set("n", "<leader>fk", builtin.keymaps)
vim.keymap.set("n", "<leader>fhi", builtin.highlights)
vim.keymap.set("n", "<leader>fa", builtin.autocommands)
vim.keymap.set("n", "<leader>fd", builtin.diagnostics)
vim.keymap.set("n", "<leader>fpf", builtin.find_files)
vim.keymap.set("n", "<leader>fgg", builtin.git_files)
vim.keymap.set("n", "<leader>flg", builtin.live_grep)

vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = "#161B20" })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = "#161B20", fg = "#121212" })
vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = "#161B20" })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { bg = "#161B20", fg = "#121212" })
vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { bg = "#161B20" })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { bg = "#161B20", fg = "#121212" })
vim.api.nvim_set_hl(0, "TelescopePromptCounter", { bg = "#161B20" })
