[colors.primary]
background = '#1d1d1d'
foreground = '#deddda'

[colors.normal]
black = '#000000'
blue = '#1C71D8'
cyan = '#33B2A4'
green = '#2EC27E'
magenta = '#9141AC'
red = '#E01B24'
white = '#DEDDDA'
yellow = '#F6D32D'

[colors.bright]
black = '#a6a69c'
blue = '#7FB4CA'
cyan = '#7AA89F'
green = '#87a987'
magenta = '#938AA9'
red = '#E46876'
white = '#c5c9c5'
yellow = '#E6C384'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

