# Base16 Kanagawa - alacritty color config
# Tommaso Laurenzi (https://github.com/rebelot)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#1f1f28'
cursor = '#dcd7ba'

# Normal colors
[colors.normal]
black = '#1f1f28'
red = '#c34043'
green = '#76946a'
yellow = '#c0a36e'
blue = '#7e9cd8'
magenta = '#957fb8'
cyan = '#6a9589'
white = '#dcd7ba'

# Bright colors
[colors.bright]
black = '#54546d'
red = '#ffa066'
green = '#16161d'
yellow = '#223249'
blue = '#727169'
magenta = '#c8c093'
cyan = '#d27e99'
white = '#717c7c'
