return {
  { 'rose-pine/neovim', name = 'rose-pine', priority = 1000 },
  { 'catppuccin/nvim', name = 'catppuccin', priority = 1000 },
  { 'Shatur/neovim-ayu', name = 'ayu', priority = 1000 },
  { 'xero/miasma.nvim', priority = 1000 },
  { 'tiagovla/tokyodark.nvim', priority = 1000 },
  { 'folke/tokyonight.nvim', priority = 1000 },
  { 'Mofiqul/vscode.nvim', priority = 1000 },
  { 'ellisonleao/gruvbox.nvim', priority = 1000 },
  { 'tjdevries/colorbuddy.nvim', priority = 1000 },
  { 'dasupradyumna/midnight.nvim', priority = 1000 },
  { 'scottmckendry/cyberdream.nvim', priority = 1000 },
  { 'bluz71/vim-moonfly-colors', name = 'moonfly', priority = 1000 },
  { 'wincent/base16-nvim', lazy = false, priority = 1000 },
  { 'nyoom-engineering/oxocarbon.nvim', lazy = false, priority = 1000 },
  { 'Mofiqul/adwaita.nvim', lazy = false, priority = 1000 },
  { 'tckmn/hotdog.vim', lazy = false, priority = 1000 },
  { 'projekt0n/github-nvim-theme', lazy = false, priority = 1000 },
}
